### ISSUE TITLE
Unable to compile on linux 

### ISSUE THREAD

**Issue by ClaudeMa** [benibela/internettools#19]
Compile fail with

> xquery.namespaces.pas(139,13) Error: Incompatible type for arg no. 2: Got "Class Of INamespace", expected "TClass"

Linux Mint 19.1 x86_64
fpc 3.0.4
Lazarus 2.0.0

Thanks

**Comment by benibela** [comment]
That happens when it is compiled with `-CR` (verify method calls). 

It is better to compile it without that option, it might cause other issues as well

**Comment by benibela** [comment]
So I have fixed the compilation.

Afterwards I got dozens of runtime errors, because I have been using a lot of breaker classes to access protected members that are not directly accessible, and -CR does not allow that. They should be fixed, too, but I do not know if I have found each of them, so it is still better to compile without -CR
